version: "3.8"

services:
  user-pages-front:
    build: ./
    command: serve -s dist
    ports:
    - 8080:5000
    restart: always

  server-ts:
    build: ./serverts
    command: npm start
    ports: 
    - 5050:5050
    restart: always
    depends_on:
    - user-pages-front
  
  